import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "references/json-rpc/debug/web-3-rpc",
    },
    {
      type: "category",
      label: "debug",
      items: [
        {
          type: "doc",
          id: "references/json-rpc/debug/chaindb-compact",
          label: "[Inspection] debug_chaindbCompact",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/chaindb-property",
          label: "[Inspection] debug_chaindbProperty",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/dump-block",
          label: "[Inspection] debug_dumpBlock",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/dump-state-trie",
          label: "[Inspection] debug_dumpStateTrie",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/get-bad-blocks",
          label: "[Inspection] debug_getBadBlocks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/get-block-rlp",
          label: "[Inspection] debug_getBlockRlp",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/get-modified-accounts-by-hash",
          label: "[Inspection] debug_getModifiedAccountsByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/get-modified-accounts-by-number",
          label: "[Inspection] debug_getModifiedAccountsByNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/get-modified-storage-nodes-by-number",
          label: "[Inspection] debug_getModifiedStorageNodesByNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/preimage",
          label: "[Inspection] debug_preimage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/print-block",
          label: "[Inspection] debug_printBlock",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/seed-hash",
          label: "[Inspection] debug_seedHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/set-head",
          label: "[Inspection] debug_setHead",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/start-collecting-trie-stats",
          label: "[Inspection] debug_startCollectingTrieStats",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/start-contract-warm-up",
          label: "[Inspection] debug_startContractWarmUp",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/start-warm-up",
          label: "[Inspection] debug_startWarmUp",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/stop-warm-up",
          label: "[Inspection] debug_stopWarmUp",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/storage-range-at",
          label: "[Inspection] debug_storageRangeAt",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/trace-bad-block",
          label: "[Trace] debug_traceBadBlock",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/trace-block",
          label: "[Trace] debug_traceBlock",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/trace-block-by-hash",
          label: "[Trace] debug_traceBlockByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/trace-block-by-number",
          label: "[Trace] debug_traceBlockByNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/trace-block-by-number-range",
          label: "[Trace] debug_traceBlockByNumberRange",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/trace-block-from-file",
          label: "[Trace] debug_traceBlockFromFile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/trace-chain",
          label: "[Trace] debug_traceChain",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/trace-transaction",
          label: "[Trace] debug_traceTransaction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/trace-call",
          label: "[Trace] debug_traceCall",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/standard-trace-bad-block-to-file",
          label: "[StandardTrace] debug_standardTraceBadBlockToFile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/standard-trace-block-to-file",
          label: "[StandardTrace] debug_standardTraceBlockToFile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/go-trace",
          label: "[RuntimeTrace] debug_goTrace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/start-go-trace",
          label: "[RuntimeTrace] debug_startGoTrace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/stop-go-trace",
          label: "[RuntimeTrace] debug_stopGoTrace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/block-profile",
          label: "[Profiling] debug_blockProfile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/cpu-profile",
          label: "[Profiling] debug_cpuProfile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/is-p-prof-running",
          label: "[Profiling] debug_isPProfRunning",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/mutex-profile",
          label: "[Profiling] debug_mutexProfile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/set-block-profile-rate",
          label: "[Profiling] debug_setBlockProfileRate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/set-mutex-profile-fraction",
          label: "[Profiling] debug_setMutexProfileFraction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/start-cpu-profile",
          label: "[Profiling] debug_startCPUProfile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/start-p-prof",
          label: "[Profiling] debug_startPProf",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/stop-cpu-profile",
          label: "[Profiling] debug_stopCPUProfile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/stop-p-prof",
          label: "[Profiling] debug_stopPProf",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/write-block-profile",
          label: "[Profiling] debug_writeBlockProfile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/write-mem-profile",
          label: "[Profiling] debug_writeMemProfile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/debug/write-mutex-profile",
          label: "[Profiling] debug_writeMutexProfile",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
