root: ./ko/docs/

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  getting_started: ./getting-started/README.md
  token_economy: ./klaytn/design/token-economy.md
  token_economy#proof-of-contribution: ./klaytn/design/token-economy.md#proof-of-contribution
  vision: ./misc/vision/README.md
