import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "references/json-rpc/klay/web-3-rpc",
    },
    {
      type: "category",
      label: "klay",
      items: [
        {
          type: "doc",
          id: "references/json-rpc/klay/account-created",
          label: "[Account] klay_accountCreated",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/accounts",
          label: "[Account] klay_accounts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/decode-account-key",
          label: "[Account] klay_decodeAccountKey",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/encode-account-key",
          label: "[Account] klay_encodeAccountKey",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-account",
          label: "[Account] klay_getAccount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-account-key",
          label: "[Account] klay_getAccountKey",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-balance",
          label: "[Account] klay_getBalance",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-code",
          label: "[Account] klay_getCode",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-transaction-count",
          label: "[Account] klay_getTransactionCount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/is-contract-account",
          label: "[Account] klay_isContractAccount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/sign",
          label: "[Account] klay_sign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/block-number",
          label: "[Block] klay_blockNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-block-by-hash",
          label: "[Block] klay_getBlockByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-block-by-number",
          label: "[Block] klay_getBlockByNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-block-receipts",
          label: "[Block] klay_getBlockReceipts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-block-transaction-count-by-hash",
          label: "[Block] klay_getBlockTransactionCountByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-block-transaction-count-by-number",
          label: "[Block] klay_getBlockTransactionCountByNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-block-with-consensus-info-by-hash",
          label: "[Block] klay_getBlockWithConsensusInfoByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-block-with-consensus-info-by-number",
          label: "[Block] klay_getBlockWithConsensusInfoByNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-block-with-consensus-info-by-number-range",
          label: "[Block] klay_getBlockWithConsensusInfoByNumberRange",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-committee",
          label: "[Block] klay_getCommittee",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-committee-size",
          label: "[Block] klay_getCommitteeSize",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-council",
          label: "[Block] klay_getCouncil",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-council-size",
          label: "[Block] klay_getCouncilSize",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-header-by-hash",
          label: "[Block] klay_getHeaderByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-header-by-number",
          label: "[Block] klay_getHeaderByNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-rewards",
          label: "[Block] klay_getRewards",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-storage-at",
          label: "[Block] klay_getStorageAt",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/syncing",
          label: "[Block] klay_syncing",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/call",
          label: "[Transaction] klay_call",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/create-access-list",
          label: "[Transaction] klay_createAccessList",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/estimate-computation-cost",
          label: "[Transaction] klay_estimateComputationCost",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/estimate-gas",
          label: "[Transaction] klay_estimateGas",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-decoded-anchoring-transaction-by-hash",
          label: "[Transaction] klay_getDecodedAnchoringTransactionByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-raw-transaction-by-block-hash-and-index",
          label: "[Transaction] klay_getRawTransactionByBlockHashAndIndex",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-raw-transaction-by-block-number-and-index",
          label: "[Transaction] klay_getRawTransactionByBlockNumberAndIndex",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-raw-transaction-by-hash",
          label: "[Transaction] klay_getRawTransactionByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-transaction-by-block-hash-and-index",
          label: "[Transaction] klay_getTransactionByBlockHashAndIndex",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-transaction-by-block-number-and-index",
          label: "[Transaction] klay_getTransactionByBlockNumberAndIndex",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-transaction-by-hash",
          label: "[Transaction] klay_getTransactionByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-transaction-by-sender-tx-hash",
          label: "[Transaction] klay_getTransactionBySenderTxHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-transaction-receipt",
          label: "[Transaction] klay_getTransactionReceipt",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-transaction-receipt-by-sender-tx-hash",
          label: "[Transaction] klay_getTransactionReceiptBySenderTxHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/pending-transactions",
          label: "[Transaction] klay_pendingTransactions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/resend",
          label: "[Transaction] klay_resend",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/send-raw-transaction",
          label: "[Transaction] klay_sendRawTransaction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/send-transaction",
          label: "[Transaction] klay_sendTransaction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/send-transaction-as-fee-payer",
          label: "[Transaction] klay_sendTransactionAsFeePayer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/sign-transaction",
          label: "[Transaction] klay_signTransaction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/sign-transaction-as-fee-payer",
          label: "[Transaction] klay_signTransactionAsFeePayer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/chain-id",
          label: "[Configuration] klay_chainID",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/client-version",
          label: "[Configuration] klay_clientVersion",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/gas-price",
          label: "[Configuration] klay_gasPrice",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/gas-price-at",
          label: "[Configuration] klay_gasPriceAt",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-chain-config",
          label: "[Configuration] klay_getChainConfig",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/is-parallel-db-write",
          label: "[Configuration] klay_isParallelDBWrite",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/is-sender-tx-hash-indexing-enabled",
          label: "[Configuration] klay_isSenderTxHashIndexingEnabled",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/protocol-version",
          label: "[Configuration] klay_protocolVersion",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/rewardbase",
          label: "[Configuration] klay_rewardbase",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-filter-changes",
          label: "[Filter] klay_getFilterChanges",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-filter-logs",
          label: "[Filter] klay_getFilterLogs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-logs",
          label: "[Filter] klay_getLogs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/new-block-filter",
          label: "[Filter] klay_newBlockFilter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/new-filter",
          label: "[Filter] klay_newFilter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/new-pending-transaction-filter",
          label: "[Filter] klay_newPendingTransactionFilter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/subscribe",
          label: "[Filter] klay_subscribe",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/uninstall-filter",
          label: "[Filter] klay_uninstallFilter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/unsubscribe",
          label: "[Filter] klay_unsubscribe",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/fee-history",
          label: "[Gas] klay_feeHistory",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/lower-bound-gas-price",
          label: "[Gas] klay_lowerBoundGasPrice",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/max-priority-fee-per-gas",
          label: "[Gas] klay_maxPriorityFeePerGas",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/upper-bound-gas-price",
          label: "[Gas] klay_upperBoundGasPrice",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-staking-info",
          label: "[Miscellaneous] klay_getStakingInfo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/node-address",
          label: "[Miscellaneous] klay_nodeAddress",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/recover-from-transaction",
          label: "[Miscellaneous] klay_recoverFromTransaction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/recover-from-message",
          label: "[Miscellaneous] klay_recoverFromMessage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/sha-3",
          label: "[Miscellaneous] klay_sha3",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/klay/get-proof",
          label: "[Miscellaneous] klay_getProof",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
