name: klaytn-docs-docusaurus dev deploy workflow
on:
  push:
    branches:
      - v2-test

jobs:
  deploy:
    name: deploy
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN_TEST }}
          role-session-name: SessionForKlaytnActions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Installing dependencies
        run: |
          yarn install

      - name: Build static files
        run: yarn build

      - name: Sync to S3 bucket and validation cloudfront
        env:
          S3_BUCKET_DEV: ${{ secrets.S3_BUCKET_TEST }}
          CLOUDFRONT_ID_DEV: ${{ secrets.CLOUDFRONT_ID_TEST }}
        run: |
          aws s3 sync ./build/ $S3_BUCKET_TEST --delete
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID_TEST --paths "/*"
